name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cache:
    path: ../cache
  equatable: ^2.0.5
  uuid: ^4.5.1
  json_serializable: ^6.8.0

  # network
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.13
