name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  user_repository:
    path: ../user_repository
  cache:
    path: ../cache

  http: ^1.2.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  mockito: ^5.4.4
  build_runner: ^2.4.13
