# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: PR Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.24.3

      - name: Install dependencies
        run: flutter pub get

      - name: Generate .env file
        run: |
          touch .env
          echo "export LOCALIZELY_API_TOKEN=${{ secrets.LOCALIZELY_API_TOKEN }}" >> .env
          echo "export CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "export CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
          echo "export CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }}" >> .env

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test

      - name: Run tests for packages
        run: flutter test packages
